jobs:
 - job: Mac
   pool:
     vmImage: 'macOS-10.13'
   steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build --info --debug'
        # checkStyleRunAnalysis: true
        # pmdRunAnalysis: true
    - script:
        ls build
      displayName: "Print options"
      condition: always()
