jobs:
 - job: Mac
   pool:
     vmImage: 'macOS-10.13'
   steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'path'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build --info --debug'
        # checkStyleRunAnalysis: true
        # pmdRunAnalysis: true
